<?
/*
- Created by Torin
- Helper functions to retrieve values in Filters table
*/

	require_once("db_config.php");

	function func_getAllFilters()
	{
		return func_getMultiRowFromTable("filters", "");
	}
	
	function func_getFilterByID($id)
	{
		$condition = "filter_id = '" . $id . "'";
		return func_getSingleRowFromTable("filters", $condition);
	}
	
	/*
	 * Returns all filters can be generated by a given module, returns raw SQL result
	 */
	function func_getFiltersByModuleID($id)
	{
		$condition = "module_id = '" . $id . "'";
		return func_getMultiRowFromTable("filters", $condition);
	}
	
	/*
	 * Returns all filters that has the given name from all modules, returns raw SQL result
	 */
	function func_getFiltersByName($name)
	{
		$condition = "filter_name = '" . $name . "'";
		return func_getMultiRowFromTable("filters", $condition);
	}
	
	function func_getFilterNameByID($id)
	{
		$condition = "filter_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("filters", $condition);
		if ($one_record == null)
			return null;
		return $one_record['filter_name'];
	}

	function func_getFilterTypeByID($id)
	{
		$condition = "filter_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("filters", $condition);
		if ($one_record == null)
			return null;
		return $one_record['filter_type'];
	}

?>