<?php
/*
- Created by Torin
- Helper functions to retrieve values in Actions table
*/

	require_once("db_config.php");

	function func_getActionByID($id)
	{
		$condition = "action_id = '" . $id . "'";
		return func_getSingleRowFromTable("actions", $condition);
	}
	
	/*
	 * Returns all actions can be generated by a given module, returns raw SQL result
	 */
	function func_getActionsByModuleID($id)
	{
		$condition = "module_id = '" . $id . "' AND action_enabled = 1";
		return func_getMultiRowFromTable("actions", $condition);
	}
	
	/*
	 * Returns all actions that has the given name from all modules, returns raw SQL result
	 */
	function func_getActionsByName($name)
	{
		$condition = "action_name = '" . $name . "'";
		return func_getMultiRowFromTable("actions", $condition);
	}
	
	function func_getActionModuleNameByID($id)
	{
		$condition = "action_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("actions", $condition);
		if ($one_record == null)
			return null;
		return intval($one_record['module_id']);
	}
	
	function func_getActionNameByID($id)
	{
		$condition = "action_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("actions", $condition);
		if ($one_record == null)
			return null;
		return $one_record['action_name'];
	}
			
	function func_getActionParamByID($id)
	{
		$condition = "action_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("actions", $condition);
		if ($one_record == null)
			return null;
		return $one_record['action_param'];
	}

?>