<?php
/*
- Created by Torin
- Helper functions to retrieve values in Triggers table
*/

	require_once("db_config.php");

	function func_getTriggerByID($id)
	{
		$condition = "trigger_id = '" . $id . "'";
		return func_getSingleRowFromTable("triggers", $condition);
	}
	
	/*
	 * Returns all triggers can be generated by a given module, returns raw SQL result
	 */
	function func_getTriggersByModuleID($id)
	{
		$condition = "module_id = '" . $id . "' AND trigger_enabled = 1";
		return func_getMultiRowFromTable("triggers", $condition);
	}
	
	/*
	 * Returns all triggers can be generated by a given module, returns raw SQL result
	 * This is more expensive than func_getTriggersByModuleID
	 */
	function func_getTriggersByModuleAlias($alias)
	{
		require_once("util_modules.php");
		$the_module = func_getModuleByAlias($alias);
		if ($the_module == null)
			return null;
		$module_id = $the_module['module_id'];
		if ($module_id == null || $module_id <= 0 || $module_id == "")
			return null;
		return func_getTriggersByModuleID($module_id);
	}
	
	/*
	 * Returns all triggers that has the given name from all modules, returns raw SQL result
	 */
	function func_getTriggersByName($name)
	{
		$condition = "trigger_name = '" . $name . "'";
		return func_getMultiRowFromTable("triggers", $condition);
	}
	
	function func_getTriggerModuleNameByID($id)
	{
		$condition = "trigger_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("triggers", $condition);
		if ($one_record == null)
			return null;
		return intval($one_record['module_id']);
	}
	
	function func_getTriggerNameByID($id)
	{
		$condition = "trigger_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("triggers", $condition);
		if ($one_record == null)
			return null;
		return $one_record['trigger_name'];
	}
	
	function func_getTriggerDescriptionByID($id)
	{
		$condition = "trigger_id = '" . $id . "'";
		$one_record = func_getSingleRowFromTable("triggers", $condition);
		if ($one_record == null)
			return null;
		return $one_record['trigger_description'];
	}
		
	//---------------------------------------------------------------------
	// ADD
	//---------------------------------------------------------------------
	
	/*
	 * Add a new trigger/trigger
	 * $trigger_id: specific pre-defined trigger in the system (unique to a $module_id)
	 * $module_id: mandatory
	 * $trigger_name: a short name of this trigger to be displayed to user, eg. disconnect, connect, new post, change
	 * $trigger_description: optional description of this trigger, will be displayed to user as tips
	 */
	function func_addTrigger($trigger_id, $user_id, $filter_id, $filter_param, $action_id, $action_param, $trigger_description)
	{	
		$table_name = "triggers";
		$id_field_name = "trigger_id";
		$input_names_array = array("module_id", "trigger_name", "trigger_description");
		$input_values_array = array($module_id, $trigger_name, $trigger_description);
		$datetime_field_name = 'last_updated';
		
		$entry_ID = func_insertSingleRecordReturnID($table_name, $id_field_name, $input_names_array, $input_values_array, $datetime_field_name);
		return $entry_ID;
	}

?>